### PR TITLE
Check boxes more material and bug FIXED #361 #365

### LINKED ISSUE #361: [PERSONALIZATION FLOW|SIGN UP|LOG IN] Make check boxes more material
Fields: 
* checkboxes 

Have user input change colors with various states, such as: 'active', 'pressed'. Right now input fields are only ever gray. Come up with a solution that works for at least APK 19. 

Colors for states: 
* active states: `<item name="teal" type="color">#00b5a9</item>`
* not active: `<item name="darkGray" type="color">#424242</item>`

### PR DESCRIPTION
**Pull request by opticod**
#361 #365

### CODE REVIEW

**Comment by zassmin** [comment]
@opticod Thanks for the PR :tada: . There are a few things: 

It doesn't resolve https://github.com/WomenWhoCode/WomenWhoCode/issues/365. I uploaded the image to show the difference. 

screen shot 2016-01-13 at 11 32 48 am

Also, the pixels look off, teal color doesn't match our [teal](https://github.com/WomenWhoCode/WomenWhoCode/blob/master/app/src/main/res/values/colors.xml#L3), and the [dark gray](https://github.com/WomenWhoCode/WomenWhoCode/blob/master/app/src/main/res/values/colors.xml#L7) border goes away in anything < than lollipop. 

screen shot 2016-01-13 at 11 33 59 am

Want to take another stab at it?

**Comment by opticod** [comment]
@zassmin Sorry for that...I have updated the checkboxes...is there need to modify Edit Text or any other thing?

File: app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java [hunk 1]
```diff
@@ -88,11 +88,15 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
...
                     // http://stackoverflow.com/questions/28047291/api21-setbuttontintlist-on-checkbox
                     cb.setButtonTintList(getContext().getResources().getColorStateList(R.color.checkbox));
+                    cb.setPadding(32, 4, 4, 4);
                 }
 
-                cb.setPadding(32, 4, 4, 4);
-                cb.setText(An);
 
+                cb.setText(An);
+                if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
```
Comment (zassmin) [inline app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java]: To resolve #365 it makes sense to get ride of the conditionals about the different version types and keep:

```
cb.setButtonDrawable(getResources().getDrawable(R.drawable.check_box_selector));
cb.setPadding(32, 16, 4, 16);
```

Also, the solution can be the same for both, it's likely worth it to put it directly onto the xml file.

File: app/src/main/res/layout/fragment_question1.xml [hunk 2]
```diff
@@ -69,7 +69,8 @@
             android:hint="Other"
             android:longClickable="false"
             android:paddingBottom="@dimen/edittext_padding"
-            android:paddingTop="@dimen/edittext_padding" />
+            android:paddingTop="@dimen/edittext_padding"
+            android:textColor="@drawable/text_selector"/>
```
Comment (zassmin) [inline app/src/main/res/layout/fragment_question1.xml]: Here, what should change is the color of the line at the bottom instead of the text.

**Comment by zassmin** [comment]
@opticod thank you! I made some more notes. The new check box is great.

File: app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java (hunk 1 above)
Comment (opticod) [inline app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java]: but if we remove 
```cb.setButtonTintList(getContext().getResources().getColorStateList(R.color.checkbox)); ```
then we will not get materialistic animated transaction which happens on checking and unchecking a checkbox after API 21 (not available below 21)

Comment (zassmin) [inline app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java]: @opticod yes, you're right! I forgot about the animations. 

Are you still trying to address bug #365? If so, this issue hasn't been resolved with this PR yet. Also, it would be really nice to have animations for at least our minsdk 16 or above.

**Comment by opticod** [comment]
@zassmin in my recent commit,I have added animation supportabe to backed apis and added drawables for different screen sizes

**Comment by zassmin** [comment]
@opticod much better! 

Few Things: 

There are a ton of files, many of the assets aren't related to the check boxes. https://github.com/opticod/WomenWhoCode/blob/master/app/src/main/res/drawable-hdpi-v11/ic_send.png, for example. 

The assets that do exist for the checkboxes are a little much, there are even some to support tv https://github.com/opticod/WomenWhoCode/blob/master/app/src/main/res/drawable-tvdpi/btn_check_to_off_mtrl_011.png which is out of scope for beta. The preferred solution that would work for each screen size without drastically increasing the amount of assets we have is 9 patch drawables. This is suggestion. 

In the interest of merging this PR, please scope down the assets to the necessary for ones for the animations. This also means removing the different screen size support.

**Comment by opticod** [comment]
@zassmin done ,i have removed the different screen size support.

**Comment by zassmin** [comment]
@opticod this is awesome!!! :dancers: :8ball:
